version: "3.8"
services:
  auth_app:
    container_name: auth_app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9001
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    networks:
      - test_network

  auth_nginx:
    container_name: auth_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
    - ./public:/usr/src/app/public
    ports:
      - 8001:8001
    depends_on:
      - auth_app
    environment:
      NGINX_FPM_HOST: auth_app
      NGINX_ROOT: /usr/src/app/public
    networks:
      - test_network

networks:
  test_network:
    external: true


